name: Continuous Deployment

on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
      - ".github/workflows/**"

jobs:
  build:
    uses: ./.github/workflows/build.yml
  lint:
    needs: build
    uses: ./.github/workflows/lint.yml
  unit:
    needs: build
    uses: ./.github/workflows/unit-test.yml
  deploy:
    needs: [lint, unit]
    uses: ./.github/workflows/deploy.yml
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      twitter_consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      twitter_consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      twitter_access_token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      twitter_access_secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
