name: Continuous Integration

on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
      - ".github/workflows/**"

jobs:
  build:
    uses: YuGiOhBot3000/yugiohbot/.github/workflows/build.yml@main
  lint:
    needs: build
    uses: YuGiOhBot3000/yugiohbot/.github/workflows/lint.yml@main
  unit:
    needs: build
    uses: YuGiOhBot3000/yugiohbot/.github/workflows/unit-test.yml@main
