name: Deploy

on:
  workflow_call:
    inputs:
      node-version:
        default: "16"
        required: false
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: Set up Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Download packages
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: packages

      - name: Apply terraform
        working-directory: packages/terraform/production
        run: |
          terraform init
          terraform apply \
            -auto-approve
