name: PR Checks

on: pull_request

jobs:
  build:
    uses: ./.github/workflows/build.yml
  lint:
    needs: build
    uses: ./.github/workflows/lint.yml
  unit:
    needs: build
    uses: ./.github/workflows/unit-test.yml
  deploy:
    needs: build
    uses: ./.github/workflows/pr-environment.yml
    with:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
