name: PR Checks

on: pull_request

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
  deploy:
    needs: checks
    uses: ./.github/workflows/pr-environment.yml
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
