name: PR Checks

on: pull_request

jobs:
  build:
    uses: ./.github/workflows/build.yml
  lint:
    needs: build
    uses: ./.github/workflows/lint.yml
  unit:
    needs: build
    uses: ./.github/workflows/unit-test.yml
