name: UnitTest

on:
  workflow_call:
    inputs:
      node-version:
        default: "16"
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - name: Download packages
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: packages

      - name: Test packages
        run: npm t --workspaces --if-present
